### ISSUE TITLE
.env

### ISSUE THREAD

**Issue by Nikollya** [gigstate/tg-chat-bot#5]
![image](https://user-images.githubusercontent.com/49242170/143496914-a6917b5a-1d04-4fd5-b2fa-e565e96740b0.png)
what to write here?

**Comment by Nikollya** [comment]
> ![image](https://user-images.githubusercontent.com/49242170/143496914-a6917b5a-1d04-4fd5-b2fa-e565e96740b0.png) what to write here?

**Comment by jamalnggau1** [comment]
i found a bug

**Comment by jamalnggau1** [comment]
*The report child pornography feature doesn't work *spam checker not working
